// ~1 500 common Brazilian Portuguese words used to pre-rank Contexto guesses.
// Replace or extend this list with a full frequency corpus (e.g. SUBTLEX-PT,
// OpenSubtitles-PT) for better rank coverage beyond the ~1 500 seeded entries.
export const PORTUGUESE_WORDS: string[] = [
  // Artigos e pronomes
  'o','a','os','as','um','uma','uns','umas',
  'eu','tu','ele','ela','nós','vocês','eles','elas',
  'me','te','se','nos','lhe','lhes','mim','ti','si',
  'meu','minha','meus','minhas','teu','tua','teus','tuas',
  'seu','sua','seus','suas','nosso','nossa','nossos','nossas',
  'este','esta','estes','estas','esse','essa','esses','essas',
  'aquele','aquela','aqueles','aquelas','aqui','aí','ali','lá',
  // Preposições e conjunções
  'de','para','com','em','por','sobre','entre','após',
  'antes','durante','sem','até','desde','sob','ante','contra',
  'e','ou','mas','porém','porque','pois','que','se','como',
  'quando','onde','quem','qual','quanto','embora','ainda',
  'então','assim','logo','também','apenas','somente','só','já',
  'nem','tanto','tão','muito','pouco','mais','menos','bem','mal',
  // Verbos comuns
  'ser','estar','ter','haver','ir','vir','poder','querer',
  'saber','dever','precisar','conseguir','fazer','dar','falar',
  'dizer','contar','perguntar','responder','ver','olhar',
  'ouvir','escutar','sentir','pensar','acreditar','conhecer',
  'entender','compreender','aprender','ensinar','estudar',
  'trabalhar','viver','morar','ficar','começar','terminar',
  'acabar','continuar','voltar','chegar','sair','entrar',
  'colocar','tirar','pegar','levar','trazer','comprar',
  'vender','comer','beber','dormir','acordar','correr',
  'andar','caminhar','voar','nadar','escrever','ler',
  'jogar','brincar','tocar','cantar','dançar','amar',
  'gostar','odiar','chorar','rir','sorrir','gritar',
  'chamar','esperar','ganhar','perder','abrir','fechar',
  'lembrar','esquecer','mudar','criar','construir','destruir',
  'ajudar','usar','encontrar','procurar','mostrar','deixar',
  'acontecer','parecer','seguir','existir','crescer','morrer',
  'nascer','matar','cair','subir','descer','ligar','desligar',
  'pagar','receber','enviar','passar','tentar','resolver',
  'decidir','escolher','descobrir','imaginar','sonhar',
  'confiar','cuidar','respeitar','proteger','defender',
  'atacar','fugir','esconder','buscar','achar','perceber',
  'notar','compartilhar','curtir','postar','baixar','carregar',
  'instalar','conectar','pesquisar','navegar','digitar','salvar',
  'deletar','copiar','colar','imprimir','enviar','receber',
  'publicar','comentar','seguir','bloquear','denunciar',
  'comprar','vender','trocar','devolver','emprestar','pedir',
  'oferecer','presentear','ganhar','perder','investir','poupar',
  'gastar','economizar','pagar','cobrar','descontar','negociar',
  'contratar','demitir','contratar','promover','aposentar',
  // Corpo humano
  'corpo','cabeça','rosto','cara','olho','olhos','nariz',
  'boca','orelha','ouvido','cabelo','pescoço','ombro',
  'braço','cotovelo','pulso','mão','mãos','dedo','dedos',
  'peito','barriga','costas','quadril','perna','joelho',
  'tornozelo','pé','pés','coração','pulmão','estômago',
  'fígado','rim','osso','músculo','pele','sangue','cérebro',
  'dente','língua','lábio','sobrancelha','testa','bochecha',
  'queixo','nuca','coluna','costela','calcanhar','coxa',
  'panturrilha','nervo','veia','artéria','intestino','bexiga',
  // Animais
  'animal','cachorro','cão','gato','cavalo','vaca','touro',
  'porco','galinha','frango','pato','pássaro','peixe',
  'tubarão','baleia','golfinho','leão','tigre','elefante',
  'girafa','macaco','urso','lobo','raposa','coelho',
  'rato','cobra','crocodilo','jacaré','sapo','borboleta',
  'abelha','formiga','mosca','mosquito','aranha','onça',
  'puma','capivara','tatu','papagaio','tucano','águia',
  'coruja','pinguim','flamingo','zebra','hipopótamo',
  'rinoceronte','gorila','tartaruga','lagarto','camelo',
  'cervo','veado','leopardo','chita','hiena','bisão',
  'alce','javali','morcego','lontra','foca','canguru',
  'coala','avestruz','peru','pombo','pardal','beija-flor',
  'gavião','falcão','pelicano','cegonha','garça','pato',
  'porco-espinho','tamanduá','preguiça','mico','sagui',
  'arara','periquito','catatua','golfinho','orca','peixe-espada',
  'piranha','lambari','tilápia','bagre','pintado','jaú',
  // Comida e bebida
  'comida','alimento','refeição','café','leite','suco',
  'água','cerveja','vinho','refrigerante','chá','arroz',
  'feijão','macarrão','pão','bolo','biscoito','sorvete',
  'chocolate','açúcar','sal','óleo','manteiga','queijo',
  'ovo','ovos','carne','camarão','lagosta','salada',
  'tomate','batata','cebola','alho','cenoura','brócolis',
  'couve','espinafre','laranja','limão','maçã','banana',
  'uva','morango','melão','melancia','abacaxi','manga',
  'goiaba','caju','açaí','guaraná','tapioca','coxinha',
  'brigadeiro','feijoada','churrasco','pizza','hambúrguer',
  'sanduíche','sopa','caldo','molho','tempero','pimenta',
  'alface','pepino','abobrinha','berinjela','beterraba',
  'milho','cogumelo','amêndoa','castanha','amendoim','nozes',
  'azeitona','presunto','salsicha','linguiça','costela',
  'picanha','alcatra','filé','fruta','verdura','legume',
  'cereal','iogurte','creme','farinha','massa','geleia',
  'mel','vinagre','mostarda','doce','salgado','sobremesa',
  'lanche','jantar','almoço','café-da-manhã','petisco','aperitivo',
  'pão-de-queijo','quindim','cocada','pamonha','curau','canjica',
  'rapadura','torta','pudim','mousse','cheesecake','crepe',
  'waffle','panqueca','omelete','quiche','risoto','paella',
  // Cores
  'cor','vermelho','azul','verde','amarelo','laranja',
  'roxo','rosa','violeta','branco','preto','cinza',
  'marrom','bege','dourado','prata','lilás','turquesa',
  'ciano','magenta','coral','salmão','índigo','carmesim',
  'escarlate','ocre','bronze','cobre','esmeralda','safira',
  'rubi','ametista','jade','oliva','vinho','caramelo',
  // Números e quantidades
  'zero','um','dois','três','quatro','cinco','seis',
  'sete','oito','nove','dez','onze','doze','treze',
  'quatorze','quinze','dezesseis','dezessete','dezoito',
  'dezenove','vinte','trinta','quarenta','cinquenta',
  'sessenta','setenta','oitenta','noventa','cem','mil',
  'milhão','bilhão','primeiro','segundo','terceiro',
  'quarto','quinto','metade','dobro','triplo','dúzia',
  'par','ímpar','dezena','centena','milhar',
  // Tempo
  'tempo','hora','minuto','segundo','dia','semana',
  'mês','ano','século','década','época','instante',
  'momento','período','fase','hoje','ontem','amanhã',
  'agora','cedo','tarde','noite','manhã','madrugada',
  'meio-dia','segunda','terça','quarta','quinta','sexta',
  'sábado','domingo','janeiro','fevereiro','março','abril',
  'maio','junho','julho','agosto','setembro','outubro',
  'novembro','dezembro','primavera','verão','outono','inverno',
  'passado','presente','futuro','antigo','moderno','recente',
  'data','calendário','prazo','agenda','horário','turno',
  // Natureza
  'natureza','terra','solo','sol','lua','estrela','planeta',
  'céu','nuvem','chuva','neve','vento','tempestade',
  'trovão','relâmpago','arco-íris','oceano','mar','rio',
  'lago','lagoa','cachoeira','montanha','vale','floresta',
  'selva','deserto','praia','ilha','continente','rocha',
  'pedra','areia','lama','planta','árvore','folha','flor',
  'raiz','caule','galho','semente','fruto','grama','mato',
  'broto','espinho','tronco','bambu','palmeira','pinheiro',
  'carvalho','eucalipto','ipê','orquídea','rosa','girassol',
  'margarida','lírio','violeta','musgo','fungo','alga',
  'recife','mangue','pântano','savana','campo','pradaria',
  'glaciar','vulcão','terremoto','furacão','tornado',
  'crepúsculo','amanhecer','horizonte','neblina','orvalho',
  'geada','granizo','vendaval','tsunami','erosão','solo',
  'mineração','petróleo','carvão','gás','energia','fóssil',
  // Casa e objetos
  'casa','lar','apartamento','quarto','sala','cozinha',
  'banheiro','jardim','varanda','teto','chão','parede',
  'porta','janela','escada','elevador','móvel','cama',
  'sofá','cadeira','mesa','armário','espelho','lâmpada',
  'televisão','computador','celular','telefone','rádio',
  'geladeira','fogão','microondas','forno','máquina','relógio',
  'livro','caderno','caneta','lápis','papel','foto','quadro',
  'tapete','almofada','travesseiro','cobertor','lençol',
  'toalha','sabão','shampoo','pente','escova','faca',
  'garfo','colher','prato','copo','panela','caixa','saco',
  'bolsa','mochila','carteira','chave','fechadura','gaveta',
  'prateleira','estante','cortina','banheira','chuveiro',
  'pia','vaso','garagem','quintal','horta','piscina',
  'churrasqueira','portão','muro','cerca','telhado','sótão',
  'porão','corredor','sala de estar','sala de jantar',
  'quarto de hóspedes','escritório','área de serviço','lavabo',
  // Pessoas e social
  'pessoa','gente','homem','mulher','criança','bebê',
  'menino','menina','adulto','adolescente','jovem','idoso',
  'família','pai','mãe','filho','filha','irmão','irmã',
  'avô','avó','neto','neta','tio','tia','primo','prima',
  'marido','esposo','esposa','namorado','namorada','noivo',
  'amigo','amiga','colega','vizinho','vizinha','cidadão',
  'povo','sociedade','comunidade','nação','governo','rei',
  'rainha','presidente','ministro','político','médico',
  'enfermeiro','professor','aluno','estudante','trabalhador',
  'empregado','chefe','patrão','funcionário','advogado',
  'juiz','policial','soldado','bombeiro','engenheiro',
  'arquiteto','artista','músico','ator','atriz','escritor',
  'jornalista','cientista','filósofo','psicólogo','terapeuta',
  'motorista','piloto','atleta','técnico','especialista',
  'gerente','diretor','sócio','parceiro','cliente','fornecedor',
  'voluntário','ativista','manifestante','eleitor','candidato',
  'deputado','senador','vereador','prefeito','governador',
  'embaixador','diplomata','agente','espião','detetive',
  // Emoções e estados mentais
  'emoção','sentimento','amor','ódio','alegria','tristeza',
  'medo','coragem','raiva','calma','ansiedade','estresse',
  'felicidade','saudade','solidão','empolgação','orgulho',
  'vergonha','culpa','surpresa','choque','alívio','inveja',
  'ciúme','esperança','admiração','desprezo','compaixão',
  'empatia','angústia','frustração','satisfação','contentamento',
  'ânimo','disposição','cansaço','preguiça','vontade','desejo',
  'sonho','imaginação','criatividade','inteligência','sabedoria',
  'confiança','lealdade','honestidade','bondade','maldade',
  'timidez','curiosidade','entusiasmo','tédio','nostalgia',
  'melancolia','euforia','pânico','terror','alívio','paz',
  'tranquilidade','agitação','nervosismo','excitação','calma',
  // Tecnologia e mídia
  'tecnologia','internet','aplicativo','programa','software',
  'hardware','tela','câmera','streaming','plataforma','rede',
  'algoritmo','dado','banco','arquivo','sistema','código',
  'programação','inteligência','artificial','robô','satélite',
  'sinal','wifi','bluetooth','carregador','bateria','memória',
  'processador','teclado','mouse','monitor','impressora',
  'microfone','fone','transmissão','podcast','canal',
  'episódio','temporada','download','upload','senha','login',
  'perfil','conta','email','mensagem','notificação','meme',
  'gif','story','feed','viral','tendência','influenciador',
  'youtuber','streamer','game','console','controle','pixel',
  'resolução','fps','lag','bug','patch','update','server',
  'nuvem','backup','criptografia','firewall','vírus','hacker',
  'selfie','vídeo','áudio','foto','filtro','edição','montagem',
  // Esportes e jogos
  'esporte','jogo','futebol','basquete','vôlei','tênis',
  'natação','corrida','ciclismo','boxe','ginástica',
  'atletismo','judô','surf','skate','handebol','golfe',
  'xadrez','videogame','time','equipe','jogador','árbitro',
  'treinador','campeão','medalha','troféu','torneio',
  'campeonato','olimpíadas','gol','ponto','placar','vitória',
  'derrota','empate','treino','exercício','força','velocidade',
  'habilidade','técnica','tática','estratégia','apito',
  'campo','quadra','piscina','pista','ringue','tatame',
  'torcida','torcedor','fãs','clássico','derby','copa',
  'mundial','seleção','clube','estádio','arena','ginásio',
  'pódio','recorde','marca','tempo','distância','salto',
  // Cultura pop e entretenimento
  'anime','mangá','cosplay','otaku','personagem','vilão',
  'herói','aventura','magia','fantasia','ficção','realidade',
  'série','filme','novela','reality','show','teatro','cinema',
  'música','banda','cantor','cantora','álbum','single','hit',
  'festival','fãs','fandom','ídolo','celebridade','famoso',
  'tendência','moda','estilo','look','dança','coreografia',
  'palco','concerto','clipe','remake','sequência','spinoff',
  'crossover','universo','saga','trilogia','coleção','edição',
  'capítulo','volume','arco','temporada','piloto','final',
  'elenco','diretor','roteirista','produtor','dublagem',
  'legenda','trailer','estreia','lançamento','bilheteria',
  'oscar','grammy','emmy','bafta','cannes','sundance',
  'samba','funk','pagode','forró','axé','baião','frevo',
  'carnaval','festa','baile','festa junina','reveillon',
  'trap','rap','hip-hop','rock','pop','eletrônico','jazz',
  'blues','reggae','sertanejo','country','gospel','mpb',
  // Educação e conhecimento
  'escola','colégio','faculdade','universidade','curso',
  'aula','lição','tarefa','prova','nota','diploma',
  'estudo','pesquisa','ciência','matemática','física',
  'química','biologia','história','geografia','literatura',
  'filosofia','arte','educação','conhecimento','aprendizagem',
  'sabedoria','teoria','prática','experimento','laboratório',
  'biblioteca','dicionário','enciclopédia','mapa','gráfico',
  'fórmula','equação','problema','solução','hipótese',
  'conclusão','análise','síntese','tese','dissertação',
  'monografia','artigo','ensaio','redação','relatório',
  'apresentação','seminário','palestra','debate','congresso',
  'bolsa','intercâmbio','intercultural','graduação','pós-graduação',
  'mestrado','doutorado','concurso','vestibular','enem',
  // Saúde e bem-estar
  'saúde','doença','medicina','hospital','clínica',
  'remédio','comprimido','cirurgia','exame','diagnóstico',
  'tratamento','cura','prevenção','sintoma','dor','febre',
  'tosse','gripe','resfriado','alergia','infecção','vírus',
  'bactéria','vacina','exercício','dieta','descanso','sono',
  'bem-estar','terapia','consulta','receita','farmácia',
  'ambulância','emergência','fisioterapia','nutrição','vitamina',
  'suplemento','proteína','carboidrato','gordura','fibra',
  'hidratação','caloria','peso','altura','pressão','glicose',
  'colesterol','triglicerídeos','hemograma','raio-x','ultrassom',
  'tomografia','ressonância','biópsia','transplante','prótese',
  'doação','sangue','plasma','órgão','doador','receptor',
  // Conceitos abstratos
  'ideia','conceito','teoria','opinião','perspectiva',
  'filosofia','ética','moral','valor','princípio','regra',
  'lei','norma','padrão','critério','objetivo','meta',
  'propósito','missão','plano','projeto','estratégia',
  'método','processo','sistema','estrutura','forma','função',
  'papel','responsabilidade','obrigação','direito','liberdade',
  'justiça','igualdade','paz','guerra','conflito','acordo',
  'aliança','cooperação','competição','poder','autoridade',
  'liderança','democracia','revolução','mudança','progresso',
  'evolução','desenvolvimento','crise','desafio','inovação',
  'verdade','mentira','realidade','ilusão','crença','fé',
  'esperança','dúvida','certeza','incerteza','risco','segurança',
  'oportunidade','ameaça','vantagem','desvantagem','benefício',
  'prejuízo','custo','lucro','investimento','retorno',
  // Adjetivos
  'bom','boa','mau','ruim','grande','pequeno','alto','baixo',
  'bonito','feio','novo','velho','rápido','lento','forte',
  'fraco','pesado','leve','quente','frio','molhado','seco',
  'limpo','sujo','claro','escuro','rico','pobre','feliz',
  'triste','animado','entediado','cansado','saudável','doente',
  'inteligente','criativo','preguiçoso','trabalhador','honesto',
  'desonesto','gentil','grosseiro','educado','corajoso','covarde',
  'generoso','egoísta','paciente','impaciente','calmo','nervoso',
  'ansioso','tranquilo','quieto','barulhento','famoso','popular',
  'importante','urgente','obrigatório','proibido','permitido',
  'possível','impossível','fácil','difícil','simples','complexo',
  'barato','caro','útil','inútil','seguro','perigoso',
  'real','fictício','antigo','moderno','natural','artificial',
  'orgânico','sintético','temporário','permanente','único',
  'comum','raro','especial','normal','extraordinário','incrível',
  'terrível','horrível','maravilhoso','fantástico','perfeito',
  'imperfeito','completo','incompleto','cheio','vazio',
  // Lugares e espaço
  'lugar','local','espaço','região','área','zona','bairro',
  'rua','avenida','praça','parque','prédio','edifício',
  'hotel','restaurante','bar','loja','mercado','shopping',
  'banco','correios','museu','galeria','teatro','cinema',
  'arena','estádio','aeroporto','porto','rodoviária','estação',
  'brasil','são paulo','rio','brasília','nordeste','sul',
  'norte','leste','oeste','centro','interior','litoral',
  'capital','estado','município','cidade','vila','comunidade',
  'campo','zona rural','subúrbio','periferia','centro','metrópole',
  'continente','hemisfério','globo','mundo','universo','galáxia',
  'sistema solar','orbita','espaço sideral','satélite','cometa',
  'asteroide','buraco negro','nebulosa','constelação',
  // Trabalho e economia
  'trabalho','emprego','cargo','salário','renda','lucro',
  'prejuízo','empresa','negócio','mercado','economia',
  'finanças','investimento','dinheiro','dívida','crédito',
  'imposto','orçamento','custo','preço','desconto','oferta',
  'demanda','produção','consumo','serviço','produto',
  'indústria','agricultura','comércio','exportação','importação',
  'globalização','capitalismo','socialismo','sindicato',
  'startup','empreendedorismo','inovação','tecnologia','digital',
  'moeda','real','dólar','euro','bitcoin','ação','bolsa',
  'banco','poupança','financiamento','hipoteca','seguro',
  // Arte e cultura
  'arte','cultura','pintura','escultura','fotografia',
  'poesia','prosa','conto','romance','crônica','poema',
  'verso','rima','ritmo','melodia','harmonia','compasso',
  'acorde','nota','instrumento','guitarra','violão','piano',
  'bateria','baixo','flauta','violino','saxofone','trompete',
  'tambor','percussão','sinfonia','ópera','coral','orquestra',
  'museu','exposição','galeria','instalação','performance',
  'graffiti','grafite','ilustração','animação','quadrinho',
  'literatura','clássico','best-seller','antologia','manuscrito',
  // Ciência e natureza
  'ciência','física','química','biologia','astronomia',
  'geologia','ecologia','genética','evolução','célula',
  'átomo','molécula','elemento','composto','reação',
  'energia','força','massa','gravidade','luz','calor',
  'eletricidade','magnetismo','som','onda','frequência',
  'temperatura','pressão','velocidade','aceleração',
  'oxigênio','hidrogênio','carbono','nitrogênio','ferro',
  'ouro','prata','cobre','platina','diamante','cristal',
  'fóssil','extinção','biodiversidade','ecossistema','habitat',
  'predador','presa','cadeia alimentar','fotossíntese','clorofila',
  'dna','gene','cromossomo','mutação','clonagem','vacina',
  // Transporte e mobilidade
  'carro','moto','bicicleta','ônibus','metrô','trem','avião',
  'navio','barco','helicóptero','submarino','foguete',
  'trânsito','estrada','rodovia','ponte','túnel','via',
  'semáforo','placa','multa','acidente','seguro','combustível',
  'gasolina','álcool','diesel','elétrico','híbrido','motor',
  'volante','freio','acelerador','embreagem','câmbio','pneu',
  'farol','retrovisor','capô','porta-malas','assento','cinto',
  // Mídia e comunicação
  'notícia','jornal','revista','televisão','rádio','internet',
  'reportagem','entrevista','editorial','coluna','artigo',
  'manchete','capa','pauta','fonte','jornalista','repórter',
  'âncora','apresentador','comentarista','analista','especialista',
  'rede social','influencer','youtuber','blogueiro','streamer',
  'live','transmissão','ao vivo','gravação','edição','publicação',
  'censura','liberdade de imprensa','fake news','desinformação',
  // Religião e espiritualidade
  'religião','fé','crença','deus','alma','espírito',
  'rezar','orar','templo','igreja','catedral','sagrado',
  'bênção','milagre','anjo','diabo','paraíso','inferno',
  'karma','dharma','meditação','yoga','espiritismo',
  'candomblé','umbanda','cristão','evangélico','católico',
  'budismo','hinduísmo','islamismo','judaísmo','ateísmo',
  'agnóstico','espiritualidade','ritual','oração','sacramento',
  'batismo','casamento','funeral','missa','culto','terreiro',
  // Política e sociedade
  'política','governo','estado','nação','república','monarquia',
  'democracia','ditadura','eleição','voto','candidato','partido',
  'esquerda','direita','centro','liberal','conservador',
  'progressista','populismo','fascismo','comunismo','anarquismo',
  'direitos humanos','igualdade','diversidade','inclusão',
  'racismo','machismo','homofobia','preconceito','discriminação',
  'protesto','manifestação','greve','revolução','golpe',
  'constituição','lei','decreto','emenda','projeto','senado',
  'câmara','congresso','supremo','ministério','secretaria',
  // Clima e ambiente
  'clima','aquecimento global','mudança climática','desmatamento',
  'queimada','poluição','reciclagem','sustentabilidade',
  'energia renovável','solar','eólica','hidrelétrica','nuclear',
  'emissão','carbono','metano','ozônio','efeito estufa',
  'biodiversidade','extinção','conservação','preservação',
  'parque nacional','reserva ambiental','mata','floresta',
  'seca','enchente','deslizamento','terremoto','vulcão',
]
